### PR TITLE
feat: add support for firecrawl

### PR DESCRIPTION
**Pull request by AmosDinh**
Linking https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/493.
This is only the basic functionality which adapts the Search Node to be able to use the firecrawl instead of plain playwright for the web search.

Can you please check that the pyproject.toml is correct? I only added the library as requirement. I think you still have to "build" it in order to appear in requirements.txt?

I also added some examples in examples/firecrawl

### CODE REVIEW

**Review by f-aguzzi — COMMENTED** [review]
Thanks for contributing. We'll have to wait for the mark of approval from the team. 

If you have the `rye` CLI installed, you can run `rye sync` and then `rye run update-requirements` in the terminal from the root of the repository. This will update the lockfiles and requirements. Otherwise, we'll do it ourselves when merging.

**Comment by AmosDinh** [comment]
Thanks for your efforts. It's a great library and I am glad to contribute, even just a little :).

Maybe you can run it, I currently have no access to my laptop.

**Comment by DiTo97** [comment]
@AmosDinh couple of remarks:
- some of the examples duplicate reading and setting env variables for seemingly no reason
- I'm a bit skeptical of adding that as a backend overall, as they have moved from being a confined scraping backend to much more with LLMs of their own
- even if the above was not a reject, I don't like having so many loaders spread out in the code unless there's a unified backend factory that makes it seamless routing from one to the other from the fetch node: if we keep adding/changing scraping backend, as it is right now, the fetch node would become a more and more convoluted sequence of if/elses, while routing to the selected scraping backend should be done elsewhere

**Comment by AmosDinh** [comment]
I think env variable setting was because if you host firecrawl locally I had difficulties for it to register them from the env file. you can avoid this by upping the langchain version to include this commit (then possible to pass key and url to the langchain function) https://github.com/langchain-ai/langchain/pull/24747/commits/dc0a2e515b74b68a349c7204e843de4c5ff95977

**Comment by AmosDinh** [comment]
I'm just using this for myself so if you're sceptical/not interested we can leave it at that.

**Pull request closed without merging**
