### PR TITLE
add html source support for source, fix "AttributeError: 'FetchNode' object has no attribute 'update_state'"

### PR DESCRIPTION
**Pull request by saied71**

### CODE REVIEW

**Review by VinciGit00 — APPROVED** [review]

**Comment by aleenprd** [comment]
Still getting this with the latest version??

**Comment by saied71** [comment]
@aleenprd 
you should install it from the source:
```bash
git clone git@github.com:ScrapeGraphAI/Scrapegraph-ai.git
cd Scrapegraph-ai/
pip install .
```

**Comment by aleenprd** [comment]
Well I installed it with Pip. I can't parse any text documents. Pinky promise ;)

**Comment by saied71** [comment]
@aleenprd 
Yes for now I think you should install it from the source as mentioned above.

**Comment by aleenprd** [comment]
Why is that? You didn't release the latest, right?

**Comment by VinciGit00** [comment]
try with this please [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/openai/md_scraper_openai.py](url)

**Pull request merged**
