### PR TITLE
feat: conditional_node

### PR DESCRIPTION
**Pull request by ekinsenler**
`conditional_node` implementation with a custom condition that can be set in the `node_config`. Also integrated into the the existing graph for the demonstration.

### CODE REVIEW

**Comment by ekinsenler** [comment]
I was unable to create a more modular solution due to the requirement of state key knowledge for condition evaluation. The node must access and evaluate specific keys within the state to function correctly, particularly when parsing and evaluating complex conditions that may include built-in functions or expressions involving state variables.

Abstracting this functionality further would limit the node's ability to perform its intended purpose, as it would not have the necessary context to evaluate conditions accurately. Therefore, this implementation strikes a balance between modularity and the practical necessity of accessing state-specific information.

I welcome any suggestions on how to improve this within the constraints

**Comment by VinciGit00** [comment]
ok please can you provide me an example of condition?

**Comment by VinciGit00** [comment]
@ekinsenler btw I think we have implemented the depth search

**Comment by ekinsenler** [comment]
Condition can be set on `node_config`
```
{
    'key_name': 'results',
    'condition': 'len(results) > 2'
}
```

Or we can just set the `key_name` that will be checked on the state if it exists

**Comment by ekinsenler** [comment]
> @ekinsenler btw I think we have implemented the depth search

Cool, is that already in beta?

**Comment by VinciGit00** [comment]
> Condition can be set on `node_config`
> 
> ```
> {
>     'key_name': 'results',
>     'condition': 'len(results) > 2'
> }
> ```
> 
> Or we can just set the `key_name` that will be checked on the state if it exists

thx, can u add it in the examples?

**Comment by VinciGit00** [comment]
> > @ekinsenler btw I think we have implemented the depth search
> 
> Cool, is that already in beta?

yes, the name is something like depth search graph

**Comment by VinciGit00** [comment]
btw @ekinsenler can u remove smart scraper cond graph and add the conditional node if a condition is present? can you do for all the graphs?

**Comment by ekinsenler** [comment]
@VinciGit00 that graph was mainly to demonstrate the usage of the `conditional_node.` And yes, it works on the other nodes aswell.

**Pull request merged**
