### PR TITLE
Added CustomOpenaiCallback to ensure exclusive access to nested data.

### PR DESCRIPTION
**Pull request by LorenzoPaleari**
See #576 for a detailed explanation.

### CODE REVIEW

**Review by VinciGit00 — APPROVED** [review]
Thank you, do you have idea of how to implement it for the other providers?

**Comment by LorenzoPaleari** [comment]
> Thank you it looks good, do you have idea of how to implement it for the other providers? I really would like to have it for Mistral and bedrock

I have taken a look at it.
For my understanding it is already working for all LLMs just by using openai_callback, the only downside is that it is not able to tell the cost of models different from OpenAi one.

I tested with Mistral and outputted the number of tokens used correctly, whiteout the price.

To add price we can mimic OpenAICallback class, just adding models names and cost should suffice to make the callback work in any situation.
https://api.python.langchain.com/en/latest/_modules/langchain_community/callbacks/openai_info.html#OpenAICallbackHandler

**Comment by VinciGit00** [comment]
Ok thx, is it ok if you implement it?

**Comment by LorenzoPaleari** [comment]
@VinciGit00 Yes, I can do that, will probably do at the end of the week.
Will also try playing around to give a more detailed view of what happens under GraphIterator, to give a more detailed view of where all this used tokens goes. I'm not sure if I can end up with a good result without interfering with function calls, will let you know

**Comment by VinciGit00** [comment]
Ok thank you so much for the effort

**Pull request merged**
