### PR TITLE
docs: add model_instance explanation 

### PR DESCRIPTION
**Pull request by goasleep**
Linking https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/560

It seems that there are examples in the documentation that use this parameter `model_instance`, but this is not particularly easy to find, so it is listed separately in the documentation.

### CODE REVIEW

**Comment by VinciGit00** [comment]
does moonshot work on scrapegraph? we did not integrated them

**Comment by f-aguzzi** [comment]
@VinciGit00 this is related to issue #560 - @goasleep wanted to use an unsupported model with an OpenAI - like API, and figured out that he could use model instances to do so. It seems to work. This means we have a new use for model instances. I suggested we could add Moonshot directly, but goalsleep didn't think it was necessary at the moment.

**Comment by f-aguzzi** [comment]
@goasleep thanks for the idea and for the contribution - we'll wait for VinciGit's opinion and then merge your pull request.

**Comment by goasleep** [comment]
Yeah. it's working  well. I did not submit unit test cases to avoid adding additional complexity because a new api key was added. Here is a test example.
image

**Comment by f-aguzzi** [comment]
Thanks a lot. Don't worry about the test cases - these things are hard to automate without having API keys for each provider. We have the same problem.

Maybe we could add a subfolder of model instance examples to the `examples` folder, though. We'll see.

**Comment by goasleep** [comment]
I sorry for adding the examples to this branch... Could you help to approval again?

**Comment by VinciGit00** [comment]
can you add also inside the folder examples/moonshor?

**Comment by goasleep** [comment]
> can you add also inside the folder examples/moonshor?

Sure. I submitted a new commit

**Pull request merged**
