### PR TITLE
687 smartscrapermulticoncatgraph error with bedrock

### PR DESCRIPTION
**Pull request by VinciGit00**

### CODE REVIEW

**Comment by rjbks** [comment]
@VinciGit00 
To fully resolve this issue (aside from further JSON formatting problem in issue), there needs ot be an update to SmartScraperMultiConcatGraph code in _create_graph line 63:

```python
smart_scraper_instance = SmartScraperGraph(
            prompt="",
            source="",
            config=self.copy_config,
            schema=self.copy_schema
        )

        graph_iterator_node = GraphIteratorNode(
            input="user_prompt & urls",
            output=["results"],
            node_config={
                "graph_instance": smart_scraper_instance,
            }
        )
```
`smart_scraper_instance` is not needed, instead, pass in uninstantiated `SmartScraperGraph` to `GraphIteratorNode` like this:
```python
graph_iterator_node = GraphIteratorNode(
            input="user_prompt & urls",
            output=["results"],
            node_config={
                "graph_instance": SmartScraperGraph,
                "scraper_config": self.copy_config,
                "scraper_schema": self.copy_schema,
            }
        )
```
NOTE: I have assumed the "scraper_schema" key, not sure that is how schema gets passed in

**Comment by VinciGit00** [comment]
hi @rjbks take a look now at the changed files

**Comment by rjbks** [comment]
> hi @rjbks take a look now at the changed files
I made a mistake, this:
```python
graph_iterator_node = GraphIteratorNode(
            input="user_prompt & urls",
            output=["results"],
            node_config={
                "graph_instance": SmartScraperGraph,
                "scraper_config": self.copy_config,
                "scraper_schema": self.copy_schema,
            }
        )
```
SHould be this:
```python
graph_iterator_node = GraphIteratorNode(
            input="user_prompt & urls",
            output=["results"],
            node_config={
                "graph_instance": SmartScraperGraph,
                "scraper_config": self.copy_config,
            },
            schema=self.copy_schema,
        )
```
Aside from that, I have applied your updates (and fixed my mistake), and it looks good. Here is the output:
```python
{'products': {'item_1': AIMessage(content='{\n  "fellowshipPrograms": "NA"\n}', additional_kwargs={'usage': {'prompt_tokens': 147, 'completion_tokens': 17, 'total_tokens': 164}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, response_metadata={'usage': {'prompt_tokens': 147, 'completion_tokens': 17, 'total_tokens': 164}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, id='run-a1065115-b8d9-424e-ac9d-c7a331a52beb-0', usage_metadata={'input_tokens': 147, 'output_tokens': 17, 'total_tokens': 164}),
  'item_2': AIMessage(content='Based on the scraped content, here is the information on the Infectious Disease Fellowship program offered:\n\n{\n  "program_name": "Infectious Disease Fellowship Program",\n  "institution": "MedStar Washington Hospital Center",\n  "duration": "2 years",\n  "current_status": "Active",\n  "date_range": "NA",\n  "key_features": [\n    "Based at largest and busiest hospital in Washington D.C.",\n    "Level I trauma center",\n    "Rotations at National Institutes of Health and Children\'s National Medical Center",\n    "Large outpatient HIV clinic",\n    "Designated Ebola Treatment Center",\n    "On-site microbiology laboratory",\n    "Transplant and device-associated infections service",\n    "Funding for conferences and board review courses",\n    "Antimicrobial stewardship curriculum"\n  ]\n}', additional_kwargs={'usage': {'prompt_tokens': 4225, 'completion_tokens': 209, 'total_tokens': 4434}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, response_metadata={'usage': {'prompt_tokens': 4225, 'completion_tokens': 209, 'total_tokens': 4434}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, id='run-e57f3e2b-0ef7-42ca-b6c5-bb891b9dc729-0', usage_metadata={'input_tokens': 4225, 'output_tokens': 209, 'total_tokens': 4434})}}
```

Usually the output is the parsed JSON, but in this case it looks like an intermediate result. Does this look correct?

**Comment by VinciGit00** [comment]
@rjbks look at it now please

**Comment by rjbks** [comment]
> @rjbks look at it now please

Looks good, any thoughts on my last question?

**Comment by VinciGit00** [comment]
are you using a schema?

**Comment by VinciGit00** [comment]
I think the main reason is because of the model

**Comment by rjbks** [comment]
> are you using a schema?

No schema, is that why?

**Comment by rjbks** [comment]
> I think the main reason is because of the model

You think it is because I am using Claude 3.5 sonnet?

**Comment by VinciGit00** [comment]
Please use the schema

**Comment by VinciGit00** [comment]
i have to close the pr, let me know if everything is ok

**Comment by rjbks** [comment]
@VinciGit00 Even with a schema this returns the same response. It does not respect the schema provided.
```python
import os
import json
import enum
from typing import List, Optional, Literal

from pydantic import BaseModel, Field

import boto3

from scrapegraphai.graphs import SmartScraperMultiConcatGraph

client = boto3.client("bedrock-runtime", region_name="us-west-2")
graph_config = {
    "llm": {
        "client": client,
        "model": "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0",
        "temperature": 0.0
    },
    'format': 'json',
    'verbose': False
}


class ProgramType(str, enum.Enum):
    RESIDENCY = "residency"
    FELLOWSHIP = "fellowship"


class Program(BaseModel):
    link: str = Field("The link (url) where this program was found")
    type: ProgramType = Field(description="The type of program this is.")  #, pattern=r'residency|fellowship')
    specialty: str = Field(description="The medical specialty on which this program focuses.")
    sub_specialty: Optional[str] = Field(description="The medical sub-specialty on which this program focuses.")
    name: str = Field(description='The name of the program.')
    institution_name: Optional[str] = Field(description='The name of the institution hosting the residency/fellowship program.')
    institution_link: Optional[str] = Field(description="The link (url) to the institution hosting the residency program.")
    institution_address: Optional[str] = Field(description='The address of the residency or fellowship program.')
    director: Optional[str] = Field(description='The director\'s name running/managing the program.')
    director_phone: Optional[str] = Field(description='The phone number of the residency or fellowship program.')
    director_email: Optional[str] = Field(description='The email address of the residency or fellowship program.')



class Result(BaseModel):
    program_links: Optional[List[str]] = Field(description="Links to fellowship or residency programs offered by this institution")
    programs: List[Program] = Field(description="List of programs (fellowships or residencies) found on this page.")


graph = SmartScraperMultiConcatGraph(
    prompt="Find information on all Fellowship and Residency programs offered, current and historic.",
    source=[
        "https://www.childrensdmc.org/health-professionals/just-for-doctors/fellowships/infectious-diseases",
        "https://www.medstarhealth.org/education/fellowship-programs/infectious-disease"
    ],
    schema=Result,
    config=graph_config
)
print(graph.run())
```
Output:
```python
{'products': {'item_1': AIMessage(content='{\n  "Fellowship_Programs": "NA",\n  "Residency_Programs": "NA",\n  "Current_Programs": "NA",\n  "Historic_Programs": "NA"\n}', additional_kwargs={'usage': {'prompt_tokens': 145, 'completion_tokens': 48, 'total_tokens': 193}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, response_metadata={'usage': {'prompt_tokens': 145, 'completion_tokens': 48, 'total_tokens': 193}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, id='run-84a21bcf-6af6-4be9-a0fb-2f8a2f952d63-0', usage_metadata={'input_tokens': 145, 'output_tokens': 48, 'total_tokens': 193}), 'item_2': AIMessage(content='Here is the JSON response based on the website content:\n\n{\n  "Fellowship Programs": [\n    {\n      "Name": "Infectious Disease Fellowship Program",\n      "Duration": "2 years",\n      "Location": "MedStar Washington Hospital Center",\n      "Description": "The MedStar Washington Hospital Center Infectious Diseases program is a 2-year training program based in the largest and busiest hospital in our nation\'s capital. It offers clinical experience in general ID consults, transplant and device-associated infections, and outpatient HIV care.",\n      "Rotations": [\n        "General consult team",\n        "Transplant / orthopedic and cardiac device infection team", \n        "NIH (stem cell transplant and highly-immunocompromised patients)",\n        "Pediatric ID consult service at Children\'s National Medical Center"\n      ],\n      "Special Features": [\n        "Joint curriculum with NIH",\n        "Ryan White-funded HIV clinic",\n        "Designated Ebola Treatment Center",\n        "On-site microbiology laboratory",\n        "Funding for conferences and board review courses",\n        "Antimicrobial stewardship curriculum"\n      ]\n    }\n  ],\n  "Residency Programs": "NA"\n}', additional_kwargs={'usage': {'prompt_tokens': 4223, 'completion_tokens': 295, 'total_tokens': 4518}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, response_metadata={'usage': {'prompt_tokens': 4223, 'completion_tokens': 295, 'total_tokens': 4518}, 'stop_reason': 'end_turn', 'model_id': 'anthropic.claude-3-5-sonnet-20240620-v1:0'}, id='run-b871daac-9436-4615-9032-bf6d19e2272d-0', usage_metadata={'input_tokens': 4223, 'output_tokens': 295, 'total_tokens': 4518})}}
```

**Comment by rjbks** [comment]
> ok, @rjbks please can you make the pull request to adjust the error?

Yes, I would need a little bit of guidance however. For example, why is there this conditional check:
```python
if not isinstance(self.llm_model, ChatBedrock):
```
Is there a specific JSON output parser for ChatBedrock, or is there no output parser for bedrock and if so what was the reason?

**Comment by VinciGit00** [comment]
No there is not a specific output parser but it's generic

**Pull request merged**
